version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/url_shortener"
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: url_shortener
      DB_PASSWORD: password
      DB_HOST: db

